package com.w3schools.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Apr 22 13:02:25 IST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConvertHttpPost {

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "FahrenheitToCelsius")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(partName = "Fahrenheit", name = "Fahrenheit", targetNamespace = "")
        java.lang.String fahrenheit
    );

    @WebResult(name = "string", targetNamespace = "http://www.w3schools.com/webservices/", partName = "Body")
    @WebMethod(operationName = "CelsiusToFahrenheit")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(partName = "Celsius", name = "Celsius", targetNamespace = "")
        java.lang.String celsius
    );
}
