package com.w3schools.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Apr 22 13:02:25 IST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.w3schools.com/webservices/", name = "TempConvertSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TempConvertSoap {

    @WebResult(name = "FahrenheitToCelsiusResult", targetNamespace = "http://www.w3schools.com/webservices/")
    @RequestWrapper(localName = "FahrenheitToCelsius", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3schools.webservices.FahrenheitToCelsius")
    @ResponseWrapper(localName = "FahrenheitToCelsiusResponse", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3schools.webservices.FahrenheitToCelsiusResponse")
    @WebMethod(operationName = "FahrenheitToCelsius", action = "http://www.w3schools.com/webservices/FahrenheitToCelsius")
    public java.lang.String fahrenheitToCelsius(
        @WebParam(name = "Fahrenheit", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String fahrenheit
    );

    @WebResult(name = "CelsiusToFahrenheitResult", targetNamespace = "http://www.w3schools.com/webservices/")
    @RequestWrapper(localName = "CelsiusToFahrenheit", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3schools.webservices.CelsiusToFahrenheit")
    @ResponseWrapper(localName = "CelsiusToFahrenheitResponse", targetNamespace = "http://www.w3schools.com/webservices/", className = "com.w3schools.webservices.CelsiusToFahrenheitResponse")
    @WebMethod(operationName = "CelsiusToFahrenheit", action = "http://www.w3schools.com/webservices/CelsiusToFahrenheit")
    public java.lang.String celsiusToFahrenheit(
        @WebParam(name = "Celsius", targetNamespace = "http://www.w3schools.com/webservices/")
        java.lang.String celsius
    );
}
